# Generated by Django 4.2.30 on 2026-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("nifi", "NiFi")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
