# Generated by Django 5.2.17 on 2026-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalidentity",
            name="glpi_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="GLPI user id (glpiID), e.g. 38 — ver Administração → Usuários no GLPI.",
                null=True,
                verbose_name="GLPI ID",
            ),
        ),
    ]
