# Generated by Django 5.2.17 on 2026-08-17 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("template_key", models.CharField(blank=True, default="", max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=120)),
                ("label", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("objectives", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("blocked", "Blocked"),
                            ("in_review", "In review"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("nifi", "NiFi")], default="manual", max_length=20
                    ),
                ),
                ("blocked_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("external_ref", models.CharField(blank=True, max_length=255)),
                ("github_repo", models.CharField(blank=True, default="", max_length=255)),
                ("github_issue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("github_issue_node_id", models.CharField(blank=True, default="", max_length=120)),
                ("github_project_item_id", models.CharField(blank=True, default="", max_length=120)),
                ("glpi_ticket_id", models.PositiveIntegerField(blank=True, null=True)),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("size", models.CharField(blank=True, default="", max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_activities",
                        to="users.externalidentity",
                    ),
                ),
                ("depends_on", models.ManyToManyField(blank=True, related_name="dependents", to="workflow.activity")),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workflow.datarelease",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ActivityTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transitions", to="workflow.activity"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(blank=True, default="#000099", max_length=20)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="workflow.datarelease"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("release", "key")},
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="workflow.releasestep"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("release", "key")},
        ),
        migrations.AddField(
            model_name="activity",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="releasestep",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
