# Generated by Django 5.2.17 on 2026-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="glpi_ticket_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
