# Generated by Django 5.2.17 on 2026-08-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_activity_glpi_ticket_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasestep",
            name="slack_thread_ts",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
