# Generated by Django 5.2.17 on 2026-08-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_activitytextrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="github_issue_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
