# Generated by Django 5.2.17 on 2026-09-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_activityworksession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityworksession",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pause", "Pause"),
                    ("play_switch", "Switched to another activity"),
                    ("review", "Sent to review"),
                    ("blocked", "Blocked"),
                    ("done", "Done"),
                    ("reassign", "Assignee changed"),
                    ("admin", "Admin"),
                    ("manual", "Manual entry"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
